services:
  ucomand-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - SPRING_PROFILES_ACTIVE=ift
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    depends_on:
      - ucomand-database


  ucomand-database:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ucomand-database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ucomand
      POSTGRES_PASSWORD: ucomand
      POSTGRES_DB: ucomand-db

volumes:
  ucomand-database_data:
