services:
  ucomand-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
