package com.example.ucomandbackend.config;

import com.example.ucomandbackend.tag.Tag;
import com.example.ucomandbackend.tag.TagRepository;
import com.example.ucomandbackend.tag.dto.TagType;
import com.example.ucomandbackend.user.User;
import com.example.ucomandbackend.user.UserRepository;
import com.example.ucomandbackend.user.dto.Gender;
import com.example.ucomandbackend.user.dto.UserRole;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.time.OffsetDateTime;
import java.util.List;

@Component
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final UserRepository userRepo;
    private final TagRepository tagRepo;

    //TODO придумать как нормально иницииализировать данные
    @Override
    @Transactional
    public void run(String... args) {
        addTags();
        addRoot();
    }

    private void addRoot() {
        if (userRepo.existsByTelegram("rootadmin")) {
            return;
        }

        var root = new User(
                1L,
                "Рут",
                "Рут",
                Gender.MALE,
                21,
                null,
                null,
                null,
                OffsetDateTime.now(),
                null,
                "rootadmin", //TODO поместить в пропертис
                UserRole.ROOT
        );
        userRepo.save(root);
    }

    private void addTags() {
        if (tagRepo.count() != 0) {
            return;
        }

        var motivationTags = List.of(
                new Tag(1L, "Без оплаты", TagType.MOTIVATION),
                new Tag(2L, "За оплату", TagType.MOTIVATION),
                new Tag(3L, "За долю", TagType.MOTIVATION),
                new Tag(4L, "Нужна практика", TagType.MOTIVATION)
        );

        var professionTags = List.of(
                new Tag(5L, "Бэкенд разработчик", TagType.PROFESSION),
                new Tag(6L, "Фронтенд разработчик", TagType.PROFESSION),
                new Tag(7L, "Веб-разработчик", TagType.PROFESSION),
                new Tag(8L, "Фулстек разработчик", TagType.PROFESSION),
                new Tag(9L, "Разработчик мобильных приложений", TagType.PROFESSION),
                new Tag(10L, "Разработчик приложений", TagType.PROFESSION),
                new Tag(11L, "Десктоп разработчик", TagType.PROFESSION),
                new Tag(12L, "Релиз менеджер", TagType.PROFESSION),
                new Tag(13L, "Разработчик игр", TagType.PROFESSION),
                new Tag(14L, "Разработчик баз данных", TagType.PROFESSION),
                new Tag(15L, "Инженер встраиваемых систем", TagType.PROFESSION),
                new Tag(16L, "HTML-верстальщик", TagType.PROFESSION),
                new Tag(17L, "Программист 1С", TagType.PROFESSION),
                new Tag(18L, "Системный инженер", TagType.PROFESSION),
                new Tag(19L, "ERP-программист", TagType.PROFESSION),
                new Tag(20L, "Архитектор программного обеспечения", TagType.PROFESSION),
                new Tag(21L, "Технический директор", TagType.PROFESSION),
                new Tag(22L, "Архитектор баз данных", TagType.PROFESSION),
                new Tag(23L, "Инженер по ручному тестированию", TagType.PROFESSION),
                new Tag(24L, "Инженер по автоматизации тестирования", TagType.PROFESSION),
                new Tag(25L, "Инженер по обеспечению качества", TagType.PROFESSION),
                new Tag(26L, "Инженер по производительности", TagType.PROFESSION),
                new Tag(27L, "UX-тестировщик", TagType.PROFESSION),
                new Tag(28L, "Аналитик по обеспечению качества", TagType.PROFESSION),
                new Tag(29L, "Менеджер по обеспечению качества", TagType.PROFESSION),
                new Tag(30L, "Директор по обеспечению качества", TagType.PROFESSION),
                new Tag(31L, "Аналитик мобильных приложений", TagType.PROFESSION),
                new Tag(32L, "Системный аналитик", TagType.PROFESSION),
                new Tag(33L, "Бизнес-аналитик", TagType.PROFESSION),
                new Tag(34L, "UX-аналитик", TagType.PROFESSION),
                new Tag(35L, "Гейм-аналитик", TagType.PROFESSION),
                new Tag(36L, "Аналитик по данным", TagType.PROFESSION),
                new Tag(37L, "Инженер по данным", TagType.PROFESSION),
                new Tag(38L, "Программный аналитик", TagType.PROFESSION),
                new Tag(39L, "Продуктовый аналитик", TagType.PROFESSION),
                new Tag(40L, "BI-разработчик", TagType.PROFESSION),
                new Tag(41L, "Веб-аналитик", TagType.PROFESSION),
                new Tag(42L, "Аналитик 1С", TagType.PROFESSION),
                new Tag(43L, "UI/UX дизайнер", TagType.PROFESSION),
                new Tag(44L, "Продуктовый дизайнер", TagType.PROFESSION),
                new Tag(45L, "Веб дизайнер", TagType.PROFESSION),
                new Tag(46L, "Графический дизайнер", TagType.PROFESSION),
                new Tag(47L, "Дизайнер приложений", TagType.PROFESSION),
                new Tag(48L, "Дизайнер иллюстратор", TagType.PROFESSION),
                new Tag(49L, "Дизайнер игр", TagType.PROFESSION),
                new Tag(50L, "Нарративный дизайнер", TagType.PROFESSION),
                new Tag(51L, "3d-аниматор", TagType.PROFESSION),
                new Tag(52L, "Моушен дизайнер", TagType.PROFESSION),
                new Tag(53L, "Flash-аниматор", TagType.PROFESSION),
                new Tag(54L, "3d моделлер", TagType.PROFESSION),
                new Tag(55L, "Художник компьютерной графики", TagType.PROFESSION),
                new Tag(56L, "VUI-дизайнер", TagType.PROFESSION),
                new Tag(57L, "Арт директор", TagType.PROFESSION),
                new Tag(58L, "Менеджер проекта", TagType.PROFESSION),
                new Tag(59L, "Директор проекта", TagType.PROFESSION),
                new Tag(60L, "Менеджер продукта", TagType.PROFESSION),
                new Tag(61L, "Scrum-мастер", TagType.PROFESSION),
                new Tag(62L, "Директор по продукту (CPO)", TagType.PROFESSION),
                new Tag(63L, "Менеджер сообщества", TagType.PROFESSION),
                new Tag(64L, "Программный менеджер", TagType.PROFESSION),
                new Tag(65L, "Директор по информационным технологиям (CIO)", TagType.PROFESSION),
                new Tag(66L, "Исполнительный директор (COO)", TagType.PROFESSION),
                new Tag(67L, "Генеральный директор (CEO)", TagType.PROFESSION),
                new Tag(68L, "Финансовый директор (CFO)", TagType.PROFESSION),
                new Tag(69L, "Pentester", TagType.PROFESSION),
                new Tag(70L, "Администратор защиты", TagType.PROFESSION),
                new Tag(71L, "Специалист по реверс-инжинирингу", TagType.PROFESSION),
                new Tag(72L, "Инженер по безопасности", TagType.PROFESSION),
                new Tag(73L, "Антифрод аналитик", TagType.PROFESSION),
                new Tag(74L, "Ученый по данным", TagType.PROFESSION),
                new Tag(75L, "ML разработчик", TagType.PROFESSION),
                new Tag(76L, "Инженер технической поддержки", TagType.PROFESSION),
                new Tag(77L, "Менеджер технической поддержки", TagType.PROFESSION),
                new Tag(78L, "Директор технической поддержки", TagType.PROFESSION),
                new Tag(79L, "Аналитик технической поддержки", TagType.PROFESSION),
                new Tag(80L, "Менеджер по обслуживанию клиентов", TagType.PROFESSION),
                new Tag(81L, "Директор по обслуживанию клиентов", TagType.PROFESSION),
                new Tag(82L, "Модератор", TagType.PROFESSION),
                new Tag(83L, "Менеджер по маркетингу", TagType.PROFESSION),
                new Tag(84L, "Директор по маркетингу", TagType.PROFESSION),
                new Tag(85L, "Маркетинговый аналитик", TagType.PROFESSION),
                new Tag(86L, "SEO-специалист", TagType.PROFESSION),
                new Tag(87L, "SMM-специалист", TagType.PROFESSION),
                new Tag(88L, "Таргетолог", TagType.PROFESSION),
                new Tag(89L, "DevRel", TagType.PROFESSION),
                new Tag(90L, "PR-менеджер", TagType.PROFESSION),
                new Tag(91L, "Контекстолог", TagType.PROFESSION),
                new Tag(92L, "Директолог", TagType.PROFESSION),
                new Tag(93L, "DevOps-инженер", TagType.PROFESSION),
                new Tag(94L, "Системный администратор", TagType.PROFESSION),
                new Tag(95L, "Администратор серверов", TagType.PROFESSION),
                new Tag(96L, "Администратор баз данных", TagType.PROFESSION),
                new Tag(97L, "Сетевой инженер", TagType.PROFESSION),
                new Tag(98L, "Администратор сайта", TagType.PROFESSION),
                new Tag(99L, "Инженер по доступности сервисов (SRE)", TagType.PROFESSION),
                new Tag(100L, "MLOps-инженер", TagType.PROFESSION),
                new Tag(101L, "Технический писатель", TagType.PROFESSION),
                new Tag(102L, "Создатель контента", TagType.PROFESSION),
                new Tag(103L, "Менеджер по контенту", TagType.PROFESSION),
                new Tag(104L, "Директор по контенту", TagType.PROFESSION),
                new Tag(105L, "Копирайтер", TagType.PROFESSION),
                new Tag(106L, "Менеджер по работе с клиентами", TagType.PROFESSION),
                new Tag(107L, "Директор по работе с клиентами", TagType.PROFESSION),
                new Tag(108L, "Менеджер по продажам", TagType.PROFESSION),
                new Tag(109L, "Директор по продажам", TagType.PROFESSION),
                new Tag(110L, "Аналитик продаж", TagType.PROFESSION),
                new Tag(111L, "Менеджер по персоналу", TagType.PROFESSION),
                new Tag(112L, "Менеджер по найму", TagType.PROFESSION),
                new Tag(113L, "Директор по персоналу", TagType.PROFESSION),
                new Tag(114L, "Директор по найму", TagType.PROFESSION),
                new Tag(115L, "Аналитик по персоналу", TagType.PROFESSION),
                new Tag(116L, "Менеджер по обучению и развитию персонала", TagType.PROFESSION),
                new Tag(117L, "Менеджер по развитию HR-бренда", TagType.PROFESSION),
                new Tag(118L, "Офис менеджер", TagType.PROFESSION),
                new Tag(119L, "Бухгалтер", TagType.PROFESSION),
                new Tag(120L, "Юрист", TagType.PROFESSION),
                new Tag(121L, "Зерокодер", TagType.PROFESSION)
        );

        var skillTags = List.of(
                new Tag(122L, "BI", TagType.SKILL),
                new Tag(123L, "B2B", TagType.SKILL),
                new Tag(124L, "B2C", TagType.SKILL),
                new Tag(125L, "B2G", TagType.SKILL),
                new Tag(126L, "BDE", TagType.SKILL),
                new Tag(127L, "BFT", TagType.SKILL),
                new Tag(128L, "BGP", TagType.SKILL),
                new Tag(129L, "Boo", TagType.SKILL),
                new Tag(130L, "Bash", TagType.SKILL),
                new Tag(131L, "BPMN", TagType.SKILL),
                new Tag(132L, "Babel", TagType.SKILL),
                new Tag(133L, "BeeGo", TagType.SKILL),
                new Tag(134L, "Behat", TagType.SKILL),
                new Tag(135L, "Blade", TagType.SKILL),
                new Tag(136L, "Boost", TagType.SKILL),
                new Tag(137L, "Bower", TagType.SKILL),
                new Tag(138L, "Box2d", TagType.SKILL),
                new Tag(139L, "Brand", TagType.SKILL),
                new Tag(140L, "BSIMM", TagType.SKILL),
                new Tag(141L, "Buddy", TagType.SKILL),
                new Tag(142L, "ZigBee", TagType.SKILL),
                new Tag(143L, "SAP BI", TagType.SKILL),
                new Tag(144L, "Blazor", TagType.SKILL),
                new Tag(145L, "Bottle", TagType.SKILL),
                new Tag(146L, "Bubble", TagType.SKILL),
                new Tag(147L, "C", TagType.SKILL),
                new Tag(148L, "C#", TagType.SKILL),
                new Tag(149L, "C++", TagType.SKILL),
                new Tag(150L, "CCS", TagType.SKILL),
                new Tag(151L, "CIO", TagType.SKILL),
                new Tag(152L, "cURL", TagType.SKILL),
                new Tag(153L, "CCNA", TagType.SKILL),
                new Tag(154L, "Chef", TagType.SKILL),
                new Tag(155L, "AVR C", TagType.SKILL),
                new Tag(156L, "Cacti", TagType.SKILL),
                new Tag(157L, "Caffe", TagType.SKILL),
                new Tag(158L, "Carrd", TagType.SKILL),
                new Tag(159L, "CI/CD", TagType.SKILL),
                new Tag(160L, "Chaos", TagType.SKILL),
                new Tag(161L, "CHILL", TagType.SKILL),
                new Tag(162L, "Clide", TagType.SKILL),
                new Tag(163L, "Cmake", TagType.SKILL),
                new Tag(164L, "Cocoa", TagType.SKILL),
                new Tag(165L, "Pure C", TagType.SKILL),
                new Tag(166L, "Canvas", TagType.SKILL),
                new Tag(167L, "FluxCD", TagType.SKILL),
                new Tag(168L, "Celery", TagType.SKILL),
                new Tag(169L, "Centos", TagType.SKILL),
                new Tag(170L, "Ceylon", TagType.SKILL),
                new Tag(171L, "D", TagType.SKILL),
                new Tag(172L, "RnD", TagType.SKILL),
                new Tag(173L, "DBA", TagType.SKILL),
                new Tag(174L, "DDD", TagType.SKILL),
                new Tag(175L, "DLT", TagType.SKILL),
                new Tag(176L, "DNS", TagType.SKILL),
                new Tag(177L, "DWH", TagType.SKILL),
                new Tag(178L, "Dart", TagType.SKILL),
                new Tag(179L, "Dash", TagType.SKILL),
                new Tag(180L, "DeFi", TagType.SKILL),
                new Tag(181L, "DHCP", TagType.SKILL),
                new Tag(182L, "DITA", TagType.SKILL),
                new Tag(183L, "Dojo", TagType.SKILL),
                new Tag(184L, "D3.js", TagType.SKILL),
                new Tag(185L, "apiDoc", TagType.SKILL),
                new Tag(186L, "WinDbg", TagType.SKILL),
                new Tag(187L, "Debian", TagType.SKILL),
                new Tag(188L, "Delphi", TagType.SKILL),
                new Tag(189L, "DevRel", TagType.SKILL),
                new Tag(190L, "DevOps", TagType.SKILL),
                new Tag(191L, "Django", TagType.SKILL),
                new Tag(192L, "Docker", TagType.SKILL),
                new Tag(193L, "Drupal", TagType.SKILL),
                new Tag(194L, "DocBook", TagType.SKILL),
                new Tag(195L, "FireDAC", TagType.SKILL),
                new Tag(196L, "Elm", TagType.SKILL),
                new Tag(197L, "ERM", TagType.SKILL),
                new Tag(198L, "ETL", TagType.SKILL),
                new Tag(199L, "Echo", TagType.SKILL),
                new Tag(200L, "Exim", TagType.SKILL),
                new Tag(201L, "Edius", TagType.SKILL),
                new Tag(202L, "Emacs", TagType.SKILL),
                new Tag(203L, "Emmet", TagType.SKILL),
                new Tag(204L, "Eiffel", TagType.SKILL),
                new Tag(205L, "Elixir", TagType.SKILL),
                new Tag(206L, "Eloqua", TagType.SKILL),
                new Tag(207L, "Erlang", TagType.SKILL),
                new Tag(208L, "Ext JS", TagType.SKILL),
                new Tag(209L, "1C: ERP", TagType.SKILL),
                new Tag(210L, "Eclipse", TagType.SKILL),
                new Tag(211L, "ECN RFC", TagType.SKILL),
                new Tag(212L, "Java EE", TagType.SKILL),
                new Tag(213L, "SAP ERP", TagType.SKILL),
                new Tag(214L, "Express", TagType.SKILL),
                new Tag(215L, "BlueEyes", TagType.SKILL),
                new Tag(216L, "Effector", TagType.SKILL),
                new Tag(217L, "Electron", TagType.SKILL),
                new Tag(218L, "Ember.js", TagType.SKILL),
                new Tag(219L, "Ethereum", TagType.SKILL),
                new Tag(220L, "MODX EVO", TagType.SKILL),
                new Tag(221L, "GCD", TagType.SKILL),
                new Tag(222L, "GIS", TagType.SKILL),
                new Tag(223L, "Gin", TagType.SKILL),
                new Tag(224L, "Git", TagType.SKILL),
                new Tag(225L, "GNU", TagType.SKILL),
                new Tag(226L, "GWT", TagType.SKILL),
                new Tag(227L, "gRPC", TagType.SKILL),
                new Tag(228L, "GIMP", TagType.SKILL),
                new Tag(229L, "GLSL", TagType.SKILL),
                new Tag(230L, "Goji", TagType.SKILL),
                new Tag(231L, "GTK+", TagType.SKILL),
                new Tag(232L, "Gulp", TagType.SKILL),
                new Tag(233L, "WebGL", TagType.SKILL),
                new Tag(234L, "Glide", TagType.SKILL),
                new Tag(235L, "Grape", TagType.SKILL),
                new Tag(236L, "GRASP", TagType.SKILL),
                new Tag(237L, "Grunt", TagType.SKILL),
                new Tag(238L, "go-chi", TagType.SKILL),
                new Tag(239L, "LibGDX", TagType.SKILL),
                new Tag(240L, "Gentoo", TagType.SKILL),
                new Tag(241L, "Gevent", TagType.SKILL),
                new Tag(242L, "Ghidra", TagType.SKILL),
                new Tag(243L, "Giotto", TagType.SKILL),
                new Tag(244L, "GitHub", TagType.SKILL),
                new Tag(245L, "Haml", TagType.SKILL),
                new Tag(246L, "Haxe", TagType.SKILL),
                new Tag(247L, "HTML", TagType.SKILL),
                new Tag(248L, "HTMX", TagType.SKILL),
                new Tag(249L, "HTTP", TagType.SKILL),
                new Tag(250L, "SW/HW", TagType.SKILL),
                new Tag(251L, "Hanami", TagType.SKILL),
                new Tag(252L, "SAP HR", TagType.SKILL),
                new Tag(253L, "Haskell", TagType.SKILL),
                new Tag(254L, "Red Hat", TagType.SKILL),
                new Tag(255L, "SAP HCM", TagType.SKILL),
                new Tag(256L, "Hexagon", TagType.SKILL),
                new Tag(257L, "Houdini", TagType.SKILL),
                new Tag(258L, "Hyper-V", TagType.SKILL),
                new Tag(259L, "Host CMS", TagType.SKILL),
                new Tag(260L, "Hibernate", TagType.SKILL),
                new Tag(261L, "AutoHotKey", TagType.SKILL),
                new Tag(262L, "ClickHouse", TagType.SKILL),
                new Tag(263L, "Handlebars", TagType.SKILL),
                new Tag(264L, "SAP Hybris", TagType.SKILL),
                new Tag(265L, "HCL AppScan", TagType.SKILL),
                new Tag(266L, "Verilog HDL", TagType.SKILL),
                new Tag(267L, "SAP S/4 HANA", TagType.SKILL),
                new Tag(268L, "Apache Hadoop", TagType.SKILL),
                new Tag(269L, "IDS", TagType.SKILL),
                new Tag(270L, "IIS", TagType.SKILL),
                new Tag(271L, "VoIP", TagType.SKILL),
                new Tag(272L, "ITIL", TagType.SKILL),
                new Tag(273L, "Ionic", TagType.SKILL),
                new Tag(274L, "OpenID", TagType.SKILL),
                new Tag(275L, "IBM Db2", TagType.SKILL),
                new Tag(276L, "IDA Pro", TagType.SKILL),
                new Tag(277L, "Infolog", TagType.SKILL),
                new Tag(278L, "Insales", TagType.SKILL),
                new Tag(279L, "Inkscape", TagType.SKILL),
                new Tag(280L, "Iptables", TagType.SKILL),
                new Tag(281L, "IBM Cloud", TagType.SKILL),
                new Tag(282L, "CSS-in-JS", TagType.SKILL),
                new Tag(283L, "Interbase", TagType.SKILL),
                new Tag(284L, "Socket.io", TagType.SKILL),
                new Tag(285L, "Dear ImGui", TagType.SKILL),
                new Tag(286L, "Integromat", TagType.SKILL),
                new Tag(287L, "Informatica", TagType.SKILL),
                new Tag(288L, "App Inventor", TagType.SKILL),
                new Tag(289L, "IBM WebSphere", TagType.SKILL),
                new Tag(290L, "Intellij IDEA", TagType.SKILL),
                new Tag(291L, "Adobe Indesign", TagType.SKILL),
                new Tag(292L, "Cocos2d-iPhone", TagType.SKILL),
                new Tag(293L, "Adobe Illustrator", TagType.SKILL),
                new Tag(294L, "Jee", TagType.SKILL),
                new Tag(295L, "JSF", TagType.SKILL),
                new Tag(296L, "JSS", TagType.SKILL),
                new Tag(297L, "J2ME", TagType.SKILL),
                new Tag(298L, "Jade", TagType.SKILL),
                new Tag(299L, "Java", TagType.SKILL),
                new Tag(300L, "JDBC", TagType.SKILL),
                new Tag(301L, "Jest", TagType.SKILL),
                new Tag(302L, "Jira", TagType.SKILL),
                new Tag(303L, "Jmix", TagType.SKILL),
                new Tag(304L, "JOOQ", TagType.SKILL),
                new Tag(305L, "JSON", TagType.SKILL),
                new Tag(306L, "JTBD", TagType.SKILL),
                new Tag(307L, "NW.js", TagType.SKILL),
                new Tag(308L, "JFrog", TagType.SKILL),
                new Tag(309L, "Jooby", TagType.SKILL),
                new Tag(310L, "Julia", TagType.SKILL),
                new Tag(311L, "Junit", TagType.SKILL),
                new Tag(312L, "FigJam", TagType.SKILL),
                new Tag(313L, "JavaFX", TagType.SKILL),
                new Tag(314L, "Vue.js", TagType.SKILL),
                new Tag(315L, "koa.js", TagType.SKILL),
                new Tag(316L, "NestJS", TagType.SKILL),
                new Tag(317L, "KVM", TagType.SKILL),
                new Tag(318L, "kPHP", TagType.SKILL),
                new Tag(319L, "Ktor", TagType.SKILL),
                new Tag(320L, "Kweb", TagType.SKILL),
                new Tag(321L, "Karma", TagType.SKILL),
                new Tag(322L, "Keras", TagType.SKILL),
                new Tag(323L, "Kerio", TagType.SKILL),
                new Tag(324L, "Kitto", TagType.SKILL),
                new Tag(325L, "Kanban", TagType.SKILL),
                new Tag(326L, "Kitura", TagType.SKILL),
                new Tag(327L, "Kotlin", TagType.SKILL),
                new Tag(328L, "Keynote", TagType.SKILL),
                new Tag(329L, "Kendo UI", TagType.SKILL),
                new Tag(330L, "VoiceKey", TagType.SKILL),
                new Tag(331L, "GitKraken", TagType.SKILL),
                new Tag(332L, "Kubernetes", TagType.SKILL),
                new Tag(333L, "Knockout.js", TagType.SKILL),
                new Tag(334L, "Apache Kafka", TagType.SKILL),
                new Tag(335L, "Linux kernel", TagType.SKILL),
                new Tag(336L, "Kohana framework", TagType.SKILL),
                new Tag(337L, "Kotlin Multiplatform", TagType.SKILL),
                new Tag(338L, "Google Kubernetes Engine", TagType.SKILL),
                new Tag(339L, "Kaspersky Endpoint Security", TagType.SKILL),
                new Tag(340L, "Lua", TagType.SKILL),
                new Tag(341L, "Lamp", TagType.SKILL),
                new Tag(342L, "LDAP", TagType.SKILL),
                new Tag(343L, "LESS", TagType.SKILL),
                new Tag(344L, "Lift", TagType.SKILL),
                new Tag(345L, "Linq", TagType.SKILL),
                new Tag(346L, "Lisp", TagType.SKILL),
                new Tag(347L, "LLVM", TagType.SKILL),
                new Tag(348L, "Lync", TagType.SKILL),
                new Tag(349L, "Latex", TagType.SKILL),
                new Tag(350L, "Linux", TagType.SKILL),
                new Tag(351L, "GitLab", TagType.SKILL),
                new Tag(352L, "Labview", TagType.SKILL),
                new Tag(353L, "Laravel", TagType.SKILL),
                new Tag(354L, "Lazarus", TagType.SKILL),
                new Tag(355L, "Leaflet", TagType.SKILL),
                new Tag(356L, "Liferay", TagType.SKILL),
                new Tag(357L, "AnyLogic", TagType.SKILL),
                new Tag(358L, "TestLink", TagType.SKILL),
                new Tag(359L, "AXI4-Lite", TagType.SKILL),
                new Tag(360L, "LogRhythm", TagType.SKILL),
                new Tag(361L, "MatPlotLib", TagType.SKILL),
                new Tag(362L, "Livestreet", TagType.SKILL),
                new Tag(363L, "Common lisp", TagType.SKILL),
                new Tag(364L, "Mac", TagType.SKILL),
                new Tag(365L, "MES", TagType.SKILL),
                new Tag(366L, "MFC", TagType.SKILL),
                new Tag(367L, "MSP", TagType.SKILL),
                new Tag(368L, "Miro", TagType.SKILL),
                new Tag(369L, "MobX", TagType.SKILL),
                new Tag(370L, "MPLS", TagType.SKILL),
                new Tag(371L, "MQTT", TagType.SKILL),
                new Tag(372L, "MVVM", TagType.SKILL),
                new Tag(373L, "Magik", TagType.SKILL),
                new Tag(374L, "Mocha", TagType.SKILL),
                new Tag(375L, "Matlab", TagType.SKILL),
                new Tag(376L, "Mobile", TagType.SKILL),
                new Tag(377L, "OpenMP", TagType.SKILL),
                new Tag(378L, "MSP430", TagType.SKILL),
                new Tag(379L, "Mudbox", TagType.SKILL),
                new Tag(380L, "3ds Max", TagType.SKILL),
                new Tag(381L, "MathCAD", TagType.SKILL),
                new Tag(382L, "MariaDB", TagType.SKILL),
                new Tag(383L, "MongoDB", TagType.SKILL),
                new Tag(384L, "Magento", TagType.SKILL),
                new Tag(385L, "Martini", TagType.SKILL),
                new Tag(386L, "MODX CMS", TagType.SKILL),
                new Tag(387L, "GNU Make", TagType.SKILL),
                new Tag(388L, "NLP", TagType.SKILL),
                new Tag(389L, "NLU", TagType.SKILL),
                new Tag(390L, ".NET", TagType.SKILL),
                new Tag(391L, "Nana", TagType.SKILL),
                new Tag(392L, "NATS", TagType.SKILL),
                new Tag(393L, "Nuke", TagType.SKILL),
                new Tag(394L, "Neo4j", TagType.SKILL),
                new Tag(395L, "Netty", TagType.SKILL),
                new Tag(396L, "Nginx", TagType.SKILL),
                new Tag(397L, "NoSQL", TagType.SKILL),
                new Tag(398L, "NumPy", TagType.SKILL),
                new Tag(399L, "Nunit", TagType.SKILL),
                new Tag(400L, "Nagios", TagType.SKILL),
                new Tag(401L, "Nerves", TagType.SKILL),
                new Tag(402L, "TestNG", TagType.SKILL),
                new Tag(403L, "NancyFX", TagType.SKILL),
                new Tag(404L, "Next.js", TagType.SKILL),
                new Tag(405L, "Node.js", TagType.SKILL),
                new Tag(406L, "Nuxt.js", TagType.SKILL),
                new Tag(407L, "Negroni", TagType.SKILL),
                new Tag(408L, "Netlist", TagType.SKILL),
                new Tag(409L, "ORM", TagType.SKILL),
                new Tag(410L, "Odoo", TagType.SKILL),
                new Tag(411L, "OLAP", TagType.SKILL),
                new Tag(412L, "z/OS", TagType.SKILL),
                new Tag(413L, "OSGI", TagType.SKILL),
                new Tag(414L, "OSPF", TagType.SKILL),
                new Tag(415L, "OData", TagType.SKILL),
                new Tag(416L, "OWASP", TagType.SKILL),
                new Tag(417L, "OpenCL", TagType.SKILL),
                new Tag(418L, "OpenCV", TagType.SKILL),
                new Tag(419L, "OpenGL", TagType.SKILL),
                new Tag(420L, "OpenVZ", TagType.SKILL),
                new Tag(421L, "OpenXR", TagType.SKILL),
                new Tag(422L, "Oracle", TagType.SKILL),
                new Tag(423L, "OpenVPN", TagType.SKILL),
                new Tag(424L, "TypeORM", TagType.SKILL),
                new Tag(425L, "TalosOS", TagType.SKILL),
                new Tag(426L, "OpenSAMM", TagType.SKILL),
                new Tag(427L, "Opencart", TagType.SKILL),
                new Tag(428L, "DevSecOps", TagType.SKILL),
                new Tag(429L, "OpenGL ES", TagType.SKILL),
                new Tag(430L, "Osi model", TagType.SKILL),
                new Tag(431L, "PHP", TagType.SKILL),
                new Tag(432L, "PLC", TagType.SKILL),
                new Tag(433L, "Ppc", TagType.SKILL),
                new Tag(434L, "PWA", TagType.SKILL),
                new Tag(435L, "Pawn", TagType.SKILL),
                new Tag(436L, "Perl", TagType.SKILL),
                new Tag(437L, "Play", TagType.SKILL),
                new Tag(438L, "Plug", TagType.SKILL),
                new Tag(439L, "Poco", TagType.SKILL),
                new Tag(440L, "PyQT", TagType.SKILL),
                new Tag(441L, "ProAV", TagType.SKILL),
                new Tag(442L, "PMBOK", TagType.SKILL),
                new Tag(443L, "Posix", TagType.SKILL),
                new Tag(444L, "Prism", TagType.SKILL),
                new Tag(445L, "Pandas", TagType.SKILL),
                new Tag(446L, "Pascal", TagType.SKILL),
                new Tag(447L, "SAP PM", TagType.SKILL),
                new Tag(448L, "Prolog", TagType.SKILL),
                new Tag(449L, "Propel", TagType.SKILL),
                new Tag(450L, "Puppet", TagType.SKILL),
                new Tag(451L, "PowerBI", TagType.SKILL),
                new Tag(452L, "R", TagType.SKILL),
                new Tag(453L, "RGB", TagType.SKILL),
                new Tag(454L, "RTL", TagType.SKILL),
                new Tag(455L, "Raku", TagType.SKILL),
                new Tag(456L, "RDMA", TagType.SKILL),
                new Tag(457L, "REST", TagType.SKILL),
                new Tag(458L, "Riak", TagType.SKILL),
                new Tag(459L, "Room", TagType.SKILL),
                new Tag(460L, "Ruby", TagType.SKILL),
                new Tag(461L, "Rust", TagType.SKILL),
                new Tag(462L, "V-Ray", TagType.SKILL),
                new Tag(463L, "React", TagType.SKILL),
                new Tag(464L, "Realm", TagType.SKILL),
                new Tag(465L, "Redis", TagType.SKILL),
                new Tag(466L, "Redux", TagType.SKILL),
                new Tag(467L, "Regex", TagType.SKILL),
                new Tag(468L, "Revel", TagType.SKILL),
                new Tag(469L, "RSpec", TagType.SKILL),
                new Tag(470L, "WinRT", TagType.SKILL),
                new Tag(471L, "Racket", TagType.SKILL),
                new Tag(472L, "Ramaze", TagType.SKILL),
                new Tag(473L, "SAS", TagType.SKILL),
                new Tag(474L, "SAP", TagType.SKILL),
                new Tag(475L, "SMB", TagType.SKILL),
                new Tag(476L, "SMM", TagType.SKILL),
                new Tag(477L, "SOA", TagType.SKILL),
                new Tag(478L, "Saas", TagType.SKILL),
                new Tag(479L, "SAML", TagType.SKILL),
                new Tag(480L, "Sass", TagType.SKILL),
                new Tag(481L, "SCSS", TagType.SKILL),
                new Tag(482L, "SFML", TagType.SKILL),
                new Tag(483L, "SIEM", TagType.SKILL),
                new Tag(484L, "Slim", TagType.SKILL),
                new Tag(485L, "Samba", TagType.SKILL),
                new Tag(486L, "Sanic", TagType.SKILL),
                new Tag(487L, "Scada", TagType.SKILL),
                new Tag(488L, "Scala", TagType.SKILL),
                new Tag(489L, "Scrum", TagType.SKILL),
                new Tag(490L, "Shell", TagType.SKILL),
                new Tag(491L, "Silex", TagType.SKILL),
                new Tag(492L, "Slick", TagType.SKILL),
                new Tag(493L, "SAP TM", TagType.SKILL),
                new Tag(494L, "Scheme", TagType.SKILL),
                new Tag(495L, "TCP", TagType.SKILL),
                new Tag(496L, "Trot", TagType.SKILL),
                new Tag(497L, "Twig", TagType.SKILL),
                new Tag(498L, "T-SQL", TagType.SKILL),
                new Tag(499L, "Tilda", TagType.SKILL),
                new Tag(500L, "TOGAF", TagType.SKILL),
                new Tag(501L, "TSLab", TagType.SKILL),
                new Tag(502L, "TYPO3", TagType.SKILL),
                new Tag(503L, "vTiger", TagType.SKILL),
                new Tag(504L, "Trello", TagType.SKILL),
                new Tag(505L, "TDD/BDD", TagType.SKILL),
                new Tag(506L, "PyTorch", TagType.SKILL),
                new Tag(507L, "Tableau", TagType.SKILL),
                new Tag(508L, "Twisted", TagType.SKILL),
                new Tag(509L, "TeamCity", TagType.SKILL),
                new Tag(510L, "Three.js", TagType.SKILL),
                new Tag(511L, "TestRail", TagType.SKILL),
                new Tag(512L, "Smart TV", TagType.SKILL),
                new Tag(513L, "Teradata", TagType.SKILL),
                new Tag(514L, "Titanium", TagType.SKILL),
                new Tag(515L, "UVM", TagType.SKILL),
                new Tag(516L, "UML", TagType.SKILL),
                new Tag(517L, "Unix", TagType.SKILL),
                new Tag(518L, "UIKit", TagType.SKILL),
                new Tag(519L, "UWSGI", TagType.SKILL),
                new Tag(520L, "Ubuntu", TagType.SKILL),
                new Tag(521L, "Uvloop", TagType.SKILL),
                new Tag(522L, "UMI.CMS", TagType.SKILL),
                new Tag(523L, "PhpUnit", TagType.SKILL),
                new Tag(524L, "SwiftUI", TagType.SKILL),
                new Tag(525L, "Unity3d", TagType.SKILL),
                new Tag(526L, "JQuery UI", TagType.SKILL),
                new Tag(527L, "AvaloniaUI", TagType.SKILL),
                new Tag(528L, "Ultimate++", TagType.SKILL),
                new Tag(529L, "UI/UX дизайн", TagType.SKILL),
                new Tag(530L, "Unreal Engine", TagType.SKILL),
                new Tag(531L, "Underscore.js", TagType.SKILL),
                new Tag(532L, "Unit-экономика", TagType.SKILL),
                new Tag(533L, "UX-копирайтинг", TagType.SKILL),
                new Tag(534L, "Тестирование UI", TagType.SKILL),
                new Tag(535L, "UX тестирование", TagType.SKILL),
                new Tag(536L, "Unix Shell Scripting", TagType.SKILL),
                new Tag(537L, "Android User Interface Guidelines", TagType.SKILL),
                new Tag(538L, "Vim", TagType.SKILL),
                new Tag(539L, "VPS", TagType.SKILL),
                new Tag(540L, "Vala", TagType.SKILL),
                new Tag(541L, "VESA", TagType.SKILL),
                new Tag(542L, "VHDL", TagType.SKILL),
                new Tag(543L, "Vapor", TagType.SKILL),
                new Tag(544L, "VK API", TagType.SKILL),
                new Tag(545L, "RISC-V", TagType.SKILL),
                new Tag(546L, "Vaadin", TagType.SKILL),
                new Tag(547L, "Vert.x", TagType.SKILL),
                new Tag(548L, "VMware", TagType.SKILL),
                new Tag(549L, "Vagrant", TagType.SKILL),
                new Tag(550L, "QlikView", TagType.SKILL),
                new Tag(551L, "VBScript", TagType.SKILL),
                new Tag(552L, "Visual C#", TagType.SKILL),
                new Tag(553L, "Voiceflow", TagType.SKILL),
                new Tag(554L, "WCF", TagType.SKILL),
                new Tag(555L, "Web", TagType.SKILL),
                new Tag(556L, "WPF", TagType.SKILL),
                new Tag(557L, "w3af", TagType.SKILL),
                new Tag(558L, "WSO2", TagType.SKILL),
                new Tag(559L, "Wowza", TagType.SKILL),
                new Tag(560L, "Wrike", TagType.SKILL),
                new Tag(561L, "WebRTC", TagType.SKILL),
                new Tag(562L, "Web 3.0", TagType.SKILL),
                new Tag(563L, "Webflow", TagType.SKILL),
                new Tag(564L, "Webpack", TagType.SKILL),
                new Tag(565L, "WebTutor", TagType.SKILL),
                new Tag(566L, "Webasyst", TagType.SKILL),
                new Tag(567L, "Win32 API", TagType.SKILL),
                new Tag(568L, "WordPress", TagType.SKILL),
                new Tag(569L, "Waterfall", TagType.SKILL),
                new Tag(570L, "WxWidgets", TagType.SKILL),
                new Tag(571L, "Wireshark", TagType.SKILL),
                new Tag(572L, "WebSockets", TagType.SKILL),
                new Tag(573L, "SolidWorks", TagType.SKILL),
                new Tag(574L, "Webinspect", TagType.SKILL),
                new Tag(575L, "Wireframes", TagType.SKILL),
                new Tag(576L, "Xen", TagType.SKILL),
                new Tag(577L, "XML", TagType.SKILL),
                new Tag(578L, "XUL", TagType.SKILL),
                new Tag(579L, "XAML", TagType.SKILL),
                new Tag(580L, "XMPP", TagType.SKILL),
                new Tag(581L, "XSLT", TagType.SKILL),
                new Tag(582L, "Xcode", TagType.SKILL),
                new Tag(583L, "XHTML", TagType.SKILL),
                new Tag(584L, "XPath", TagType.SKILL),
                new Tag(585L, "X86 asm", TagType.SKILL),
                new Tag(586L, "DirectX", TagType.SKILL),
                new Tag(587L, "Xamarin", TagType.SKILL),
                new Tag(588L, "Cocos2d-x", TagType.SKILL),
                new Tag(589L, "QuarkXPress", TagType.SKILL),
                new Tag(590L, "Microsoft Xna", TagType.SKILL),
                new Tag(591L, "Final Cut Pro X", TagType.SKILL),
                new Tag(592L, "Xen Cloud Platform", TagType.SKILL),
                new Tag(593L, "Yupe", TagType.SKILL),
                new Tag(594L, "YouTrack", TagType.SKILL),
                new Tag(595L, "Yandex.Cloud", TagType.SKILL),
                new Tag(596L, "Yii framework", TagType.SKILL),
                new Tag(597L, "Yocto Project", TagType.SKILL),
                new Tag(598L, "Yandex DataLens", TagType.SKILL),
                new Tag(599L, "Yandex Database", TagType.SKILL),
                new Tag(600L, "Zabbix", TagType.SKILL),
                new Tag(601L, "Zapier", TagType.SKILL),
                new Tag(602L, "ZBrush", TagType.SKILL),
                new Tag(603L, "Zeplin", TagType.SKILL),
                new Tag(604L, "Zennoposter", TagType.SKILL),
                new Tag(605L, "Zend Framework", TagType.SKILL),
                new Tag(606L, "Zurb foundation", TagType.SKILL),
                new Tag(607L, "АСУ ТП", TagType.SKILL),
                new Tag(608L, "Алгоритмы", TagType.SKILL),
                new Tag(609L, "2d-анимация", TagType.SKILL),
                new Tag(610L, "3d анимация", TagType.SKILL),
                new Tag(611L, "Концепт-арт", TagType.SKILL),
                new Tag(612L, "Анализ угроз", TagType.SKILL),
                new Tag(613L, "Анализ данных", TagType.SKILL),
                new Tag(614L, "Веб аналитика", TagType.SKILL),
                new Tag(615L, "Арт-директинг", TagType.SKILL),
                new Tag(616L, "Английский язык", TagType.SKILL),
                new Tag(617L, "SEO-аудит сайтов", TagType.SKILL),
                new Tag(618L, "Системный анализ", TagType.SKILL),
                new Tag(619L, "Бизнес аналитика", TagType.SKILL),
                new Tag(620L, "Адаптивный дизайн", TagType.SKILL),
                new Tag(621L, "Анализ требований", TagType.SKILL),
                new Tag(622L, "Создание анимации", TagType.SKILL),
                new Tag(623L, "Адаптивная верстка", TagType.SKILL),
                new Tag(624L, "Адаптация персонала", TagType.SKILL),
                new Tag(625L, "Системная аналитика", TagType.SKILL),
                new Tag(626L, "Анимация персонажей", TagType.SKILL),
                new Tag(627L, "Администрирование 1С", TagType.SKILL),
                new Tag(628L, "Финансовая аналитика", TagType.SKILL),
                new Tag(629L, "Академический рисунок", TagType.SKILL),
                new Tag(630L, "Продуктовая аналитика", TagType.SKILL),
                new Tag(631L, "Юзабилити-аудит сайта", TagType.SKILL),
                new Tag(632L, "БЭМ", TagType.SKILL),
                new Tag(633L, "Битрикс24", TagType.SKILL),
                new Tag(634L, "Баг-трекинг", TagType.SKILL),
                new Tag(635L, "Базы данных", TagType.SKILL),
                new Tag(636L, "Ведение блога", TagType.SKILL),
                new Tag(637L, "Брендирование", TagType.SKILL),
                new Tag(638L, "Большие данные", TagType.SKILL),
                new Tag(639L, "CMS «1С-Битрикс»", TagType.SKILL),
                new Tag(640L, "Развитие бизнеса", TagType.SKILL),
                new Tag(641L, "Создание баннеров", TagType.SKILL),
                new Tag(642L, "Безопасность сетей", TagType.SKILL),
                new Tag(643L, "Бережливый стартап", TagType.SKILL),
                new Tag(644L, "Создание чат-ботов", TagType.SKILL),
                new Tag(645L, "Бизнес-планирование", TagType.SKILL),
                new Tag(646L, "Сетевая безопасность", TagType.SKILL),
                new Tag(647L, "Бизнес-моделирование", TagType.SKILL),
                new Tag(648L, "Создание telegram-ботов", TagType.SKILL),
                new Tag(649L, "Бережливое производство", TagType.SKILL),
                new Tag(650L, "Беспроводные технологии", TagType.SKILL),
                new Tag(651L, "Бизнес-консультирование", TagType.SKILL),
                new Tag(652L, "Бюджетирование проектов", TagType.SKILL),
                new Tag(653L, "Проектирование баз данных", TagType.SKILL),
                new Tag(654L, "Построение бизнес-моделей", TagType.SKILL),
                new Tag(655L, "Описание бизнес-процессов", TagType.SKILL),
                new Tag(656L, "ВКС", TagType.SKILL),
                new Tag(657L, "Веб-дизайн", TagType.SKILL),
                new Tag(658L, "Видеодизайн", TagType.SKILL),
                new Tag(659L, "Верстка книг", TagType.SKILL),
                new Tag(660L, "Съемка видео", TagType.SKILL),
                new Tag(661L, "Монтаж видео", TagType.SKILL),
                new Tag(662L, "Визуализация", TagType.SKILL),
                new Tag(663L, "Внедрение CRM", TagType.SKILL),
                new Tag(664L, "Верстка Email", TagType.SKILL),
                new Tag(665L, "Видеостриминг", TagType.SKILL),
                new Tag(666L, "Виртуализация", TagType.SKILL),
                new Tag(667L, "Веб-разработка", TagType.SKILL),
                new Tag(668L, "Работа в команде", TagType.SKILL),
                new Tag(669L, "Валидная верстка", TagType.SKILL),
                new Tag(670L, "Создание визиток", TagType.SKILL),
                new Tag(671L, "Преподавание в IT", TagType.SKILL),
                new Tag(672L, "Семантический веб", TagType.SKILL),
                new Tag(673L, "Векторная графика", TagType.SKILL),
                new Tag(674L, "Верстка лендингов", TagType.SKILL),
                new Tag(675L, "Вирусный маркетинг", TagType.SKILL),
                new Tag(676L, "Ведение переговоров", TagType.SKILL),
                new Tag(677L, "Внешняя оптимизация", TagType.SKILL),
                new Tag(678L, "Датамайнинг", TagType.SKILL),
                new Tag(679L, "Персональные данные", TagType.SKILL),
                new Tag(680L, "Сеть хранения данных", TagType.SKILL),
                new Tag(681L, "Администрирование баз данных", TagType.SKILL),
                new Tag(682L, "Алгоритмы и структуры данных", TagType.SKILL),
                new Tag(683L, "ЕСКД", TagType.SKILL),
                new Tag(684L, "ЕСПД", TagType.SKILL),
                new Tag(685L, "Обработка естественного языка", TagType.SKILL),
                new Tag(686L, "Живопись", TagType.SKILL),
                new Tag(687L, "Журналистика", TagType.SKILL),
                new Tag(688L, "Цифровая живопись", TagType.SKILL),
                new Tag(689L, "Зерокодинг", TagType.SKILL),
                new Tag(690L, "Защита от DDOS", TagType.SKILL),
                new Tag(691L, "Звукорежиссура", TagType.SKILL),
                new Tag(692L, "Обработка звука", TagType.SKILL),
                new Tag(693L, "Защита информации", TagType.SKILL),
                new Tag(694L, "Компьютерное зрение", TagType.SKILL),
                new Tag(695L, "Создание звуковых эффектов", TagType.SKILL),
                new Tag(696L, "Алгоритмическая закупка рекламы", TagType.SKILL),
                new Tag(697L, "Разработка систем защиты информации", TagType.SKILL),
                new Tag(698L, "Дизайн игр", TagType.SKILL),
                new Tag(699L, "Дизайн иконок", TagType.SKILL),
                new Tag(700L, "API Интерфейсы", TagType.SKILL),
                new Tag(701L, "Генерация идей", TagType.SKILL),
                new Tag(702L, "Разработка игр", TagType.SKILL),
                new Tag(703L, "Испанский язык", TagType.SKILL),
                new Tag(704L, "Графика для игр", TagType.SKILL),
                new Tag(705L, "Создание иконок", TagType.SKILL),
                new Tag(706L, "Дизайн интерьера", TagType.SKILL),
                new Tag(707L, "Интернет маркетинг", TagType.SKILL),
                new Tag(708L, "Исследование рынка", TagType.SKILL),
                new Tag(709L, "Проведение интервью", TagType.SKILL),
                new Tag(710L, "Венчурные инвестиции", TagType.SKILL),
                new Tag(711L, "Интерактивный дизайн", TagType.SKILL),
                new Tag(712L, "Написание инструкций", TagType.SKILL),
                new Tag(713L, "Системная интеграция", TagType.SKILL),
                new Tag(714L, "Создание инфографики", TagType.SKILL),
                new Tag(715L, "Информационный дизайн", TagType.SKILL),
                new Tag(716L, "Обработка изображений", TagType.SKILL),
                new Tag(717L, "Программная инженерия", TagType.SKILL),
                new Tag(718L, "Разработка под AR и VR", TagType.SKILL),
                new Tag(719L, "Работа с аудио и видео", TagType.SKILL),
                new Tag(720L, "Редактура и корректура", TagType.SKILL),
                new Tag(721L, "Управление изменениями", TagType.SKILL),
                new Tag(722L, "КСАС", TagType.SKILL),
                new Tag(723L, "Коучинг", TagType.SKILL),
                new Tag(724L, "Компас 3d", TagType.SKILL),
                new Tag(725L, "Композинг", TagType.SKILL),
                new Tag(726L, "Компоновка", TagType.SKILL),
                new Tag(727L, "Каллиграфия", TagType.SKILL),
                new Tag(728L, "Компиляторы", TagType.SKILL),
                new Tag(729L, "Копирайтинг", TagType.SKILL),
                new Tag(730L, "Криптография", TagType.SKILL),
                new Tag(731L, "Просмотр кода", TagType.SKILL),
                new Tag(732L, "Китайский язык", TagType.SKILL),
                new Tag(733L, "Коллажирование", TagType.SKILL),
                new Tag(734L, "Подбор команды", TagType.SKILL),
                new Tag(735L, "API Яндекс.Карты", TagType.SKILL),
                new Tag(736L, "Дизайн концептов", TagType.SKILL),
                new Tag(737L, "Оптимизация кода", TagType.SKILL),
                new Tag(738L, "Консультирование", TagType.SKILL),
                new Tag(739L, "Контроль качества", TagType.SKILL),
                new Tag(740L, "Создание комиксов", TagType.SKILL),
                new Tag(741L, "Контент маркетинг", TagType.SKILL),
                new Tag(742L, "Поддержка клиентов", TagType.SKILL),
                new Tag(743L, "Леттеринг", TagType.SKILL),
                new Tag(744L, "Лидогенерация", TagType.SKILL),
                new Tag(745L, "Локализация ПО", TagType.SKILL),
                new Tag(746L, "Дизайн логотипов", TagType.SKILL),
                new Tag(747L, "Дизайн лендингов", TagType.SKILL),
                new Tag(748L, "Литературное редактирование", TagType.SKILL),
                new Tag(749L, "Проектирование и прокладка ЛВС", TagType.SKILL),
                new Tag(750L, "Модель C4", TagType.SKILL),
                new Tag(751L, "Математика", TagType.SKILL),
                new Tag(752L, "Мониторинг", TagType.SKILL),
                new Tag(753L, "Новые медиа", TagType.SKILL),
                new Tag(754L, "Маршрутизация", TagType.SKILL),
                new Tag(755L, "Моделирование", TagType.SKILL),
                new Tag(756L, "Модерирование", TagType.SKILL),
                new Tag(757L, "Цифровые медиа", TagType.SKILL),
                new Tag(758L, "Яндекс.Метрика", TagType.SKILL),
                new Tag(759L, "Мультипликация", TagType.SKILL),
                new Tag(760L, "Email маркетинг", TagType.SKILL),
                new Tag(761L, "Многопоточность", TagType.SKILL),
                new Tag(762L, "3d моделирование", TagType.SKILL),
                new Tag(763L, "Управление медиа", TagType.SKILL),
                new Tag(764L, "Медийная реклама", TagType.SKILL),
                new Tag(765L, "Мониторинг сетей", TagType.SKILL),
                new Tag(766L, "Написание музыки", TagType.SKILL),
                new Tag(767L, "Машинное обучение", TagType.SKILL),
                new Tag(768L, "Медиапланирование", TagType.SKILL),
                new Tag(769L, "Монтаж систем связи", TagType.SKILL),
                new Tag(770L, "SAP НСИ", TagType.SKILL),
                new Tag(771L, "Нейминг", TagType.SKILL),
                new Tag(772L, "Настройка RSS", TagType.SKILL),
                new Tag(773L, "Настройка VPN", TagType.SKILL),
                new Tag(774L, "Немецкий язык", TagType.SKILL),
                new Tag(775L, "Наставничество", TagType.SKILL),
                new Tag(776L, "Нейронные сети", TagType.SKILL),
                new Tag(777L, "Настройка Proxy", TagType.SKILL),
                new Tag(778L, "Написание сценариев", TagType.SKILL),
                new Tag(779L, "Дизайн наружной рекламы", TagType.SKILL),
                new Tag(780L, "Нагрузочное тестирование", TagType.SKILL),
                new Tag(781L, "Настройка офисных мини-атс", TagType.SKILL),
                new Tag(782L, "Настройка оборудования Cisco", TagType.SKILL),
                new Tag(783L, "Тестирование на проникновение", TagType.SKILL),
                new Tag(784L, "Научно-исследовательская работа", TagType.SKILL),
                new Tag(785L, "Низкоуровневое программирование", TagType.SKILL),
                new Tag(786L, "Настройка и наладка оборудования", TagType.SKILL),
                new Tag(787L, "Низкополигональное моделирование", TagType.SKILL),
                new Tag(788L, "Настройка и ремонт компьютерной техники", TagType.SKILL),
                new Tag(789L, "ООП", TagType.SKILL),
                new Tag(790L, "Озвучивание", TagType.SKILL),
                new Tag(791L, "Охрана труда", TagType.SKILL),
                new Tag(792L, "SEO-оптимизация", TagType.SKILL),
                new Tag(793L, "Обработка резюме", TagType.SKILL),
                new Tag(794L, "Рисование от руки", TagType.SKILL),
                new Tag(795L, "Обучение персонала", TagType.SKILL),
                new Tag(796L, "Облачные вычисления", TagType.SKILL),
                new Tag(797L, "Обратная разработка", TagType.SKILL),
                new Tag(798L, "Обеспечение качества", TagType.SKILL),
                new Tag(799L, "Обработка фотографий", TagType.SKILL),
                new Tag(800L, "Обслуживание клиентов", TagType.SKILL),
                new Tag(801L, "Поисковая оптимизация", TagType.SKILL),
                new Tag(802L, "Внутренняя оптимизация", TagType.SKILL),
                new Tag(803L, "Организация мероприятий", TagType.SKILL),
                new Tag(804L, "Связи с общественностью", TagType.SKILL),
                new Tag(805L, "Организация работы с CRM", TagType.SKILL),
                new Tag(806L, "Ремонт и обслуживание ПК", TagType.SKILL),
                new Tag(807L, "Парсинг", TagType.SKILL),
                new Tag(808L, "Презентации", TagType.SKILL),
                new Tag(809L, "Планирование", TagType.SKILL),
                new Tag(810L, "Слепая печать", TagType.SKILL),
                new Tag(811L, "Прикладное ПО", TagType.SKILL),
                new Tag(812L, "Приоритизация", TagType.SKILL),
                new Tag(813L, "Плоский дизайн", TagType.SKILL),
                new Tag(814L, "Поиск талантов", TagType.SKILL),
                new Tag(815L, "HTML-приложения", TagType.SKILL),
                new Tag(816L, "Дизайн продукта", TagType.SKILL),
                new Tag(817L, "Тестирование ПО", TagType.SKILL),
                new Tag(818L, "Решение проблем", TagType.SKILL),
                new Tag(819L, "Поддержка сайтов", TagType.SKILL),
                new Tag(820L, "Разработка под 1С", TagType.SKILL),
                new Tag(821L, "Текстовый перевод", TagType.SKILL),
                new Tag(822L, "Разработка под iOS", TagType.SKILL),
                new Tag(823L, "Пиксельная графика", TagType.SKILL),
                new Tag(824L, "Построение команды", TagType.SKILL),
                new Tag(825L, "Рендеринг", TagType.SKILL),
                new Tag(826L, "Рисование", TagType.SKILL),
                new Tag(827L, "Раскадровка", TagType.SKILL),
                new Tag(828L, "Русский язык", TagType.SKILL),
                new Tag(829L, "Разработка ТЗ", TagType.SKILL),
                new Tag(830L, "Ретуширование", TagType.SKILL),
                new Tag(831L, "Разработка CRM", TagType.SKILL),
                new Tag(832L, "Разработчик RPA", TagType.SKILL),
                new Tag(833L, "Раскрутка сайтов", TagType.SKILL),
                new Tag(834L, "Растровая графика", TagType.SKILL),
                new Tag(835L, "Разработка шрифтов", TagType.SKILL),
                new Tag(836L, "Управление рисками", TagType.SKILL),
                new Tag(837L, "Контекстная реклама", TagType.SKILL),
                new Tag(838L, "САПР", TagType.SKILL),
                new Tag(839L, "Сокеты", TagType.SKILL),
                new Tag(840L, "С++ builder", TagType.SKILL),
                new Tag(841L, "Objective-С", TagType.SKILL),
                new Tag(842L, "Саунд-дизайн", TagType.SKILL),
                new Tag(843L, "Дизайн-система", TagType.SKILL),
                new Tag(844L, "Диаграммы связей", TagType.SKILL),
                new Tag(845L, "Создание скетчей", TagType.SKILL),
                new Tag(846L, "Создание чертежей", TagType.SKILL),
                new Tag(847L, "Типографика", TagType.SKILL),
                new Tag(848L, "Яндекс Трекер", TagType.SKILL),
                new Tag(849L, "Текстурирование", TagType.SKILL),
                new Tag(850L, "A/B тестирование", TagType.SKILL),
                new Tag(851L, "Тестирование API", TagType.SKILL),
                new Tag(852L, "Телекоммуникации", TagType.SKILL),
                new Tag(853L, "Технический дизайн", TagType.SKILL),
                new Tag(854L, "Сетевые технологии", TagType.SKILL),
                new Tag(855L, "Технический перевод", TagType.SKILL),
                new Tag(856L, "Ручное тестирование", TagType.SKILL),
                new Tag(857L, "Тестирование сайтов", TagType.SKILL),
                new Tag(858L, "Тестирование дизайна", TagType.SKILL),
                new Tag(859L, "Технический директор", TagType.SKILL),
                new Tag(860L, "Техническая поддержка", TagType.SKILL),
                new Tag(861L, "Разработка тест-кейсов", TagType.SKILL),
                new Tag(862L, "Дизайн уровней", TagType.SKILL),
                new Tag(863L, "Дизайн упаковки", TagType.SKILL),
                new Tag(864L, "Продажи HR-услуг", TagType.SKILL),
                new Tag(865L, "Управление людьми", TagType.SKILL),
                new Tag(866L, "Управление компанией", TagType.SKILL),
                new Tag(867L, "Управление контентом", TagType.SKILL),
                new Tag(868L, "Управление проектами", TagType.SKILL),
                new Tag(869L, "Управление событиями", TagType.SKILL),
                new Tag(870L, "Управление продуктами", TagType.SKILL),
                new Tag(871L, "Управление IT-услугами", TagType.SKILL),
                new Tag(872L, "Управление программами", TagType.SKILL),
                new Tag(873L, "Управление разработкой", TagType.SKILL),
                new Tag(874L, "Ведение воинского учета", TagType.SKILL),
                new Tag(875L, "Стратегическое управление", TagType.SKILL),
                new Tag(876L, "Конфигурационное управление", TagType.SKILL),
                new Tag(877L, "Управление бизнес-процессами", TagType.SKILL),
                new Tag(878L, "Управление требованиями к ПО", TagType.SKILL),
                new Tag(879L, "Установка и обслуживание офисной техники", TagType.SKILL),
                new Tag(880L, "Цветокоррекция", TagType.SKILL),
                new Tag(881L, "Синхронная цифровая иерархия", TagType.SKILL),
                new Tag(882L, "Цифровой сигнальный процессор", TagType.SKILL),
                new Tag(883L, "Программирование ЧПУ", TagType.SKILL),
                new Tag(884L, "Разработка через тестирование", TagType.SKILL),
                new Tag(885L, "Шаблон проектирования", TagType.SKILL),
                new Tag(886L, "Библиотека стандартных шаблонов", TagType.SKILL),
                new Tag(887L, "Электронная коммерция", TagType.SKILL),
                new Tag(888L, "Разработка электроники", TagType.SKILL),
                new Tag(889L, "Создание визуальных эффектов", TagType.SKILL),
                new Tag(890L, "Эзотерические языки программирования", TagType.SKILL),
                new Tag(891L, "Юриспруденция", TagType.SKILL),
                new Tag(892L, "Яндекс директ", TagType.SKILL),
                new Tag(893L, "Французский язык", TagType.SKILL),
                new Tag(894L, "Составление семантического ядра", TagType.SKILL),
                new Tag(895L, "Processing (язык программирования)", TagType.SKILL),
                new Tag(896L, "SQL", TagType.SKILL),
                new Tag(897L, "Python", TagType.SKILL),
                new Tag(898L, "PostgreSQL", TagType.SKILL),
                new Tag(899L, "MySQL", TagType.SKILL),
                new Tag(900L, "Java Spring Framework", TagType.SKILL),
                new Tag(901L, "Mongo", TagType.SKILL),
                new Tag(902L, "DB", TagType.SKILL),
                new Tag(903L, "Golang", TagType.SKILL),
                new Tag(904L, "Spring Boot", TagType.SKILL),
                new Tag(905L, "CSS", TagType.SKILL),
                new Tag(906L, "TypeScript", TagType.SKILL),
                new Tag(907L, "JQuery", TagType.SKILL),
                new Tag(908L, "Кроссбраузерная верстка", TagType.SKILL),
                new Tag(909L, "Twitter Bootstrap", TagType.SKILL),
                new Tag(910L, "React Native", TagType.SKILL),
                new Tag(911L, "JavaScript", TagType.SKILL),
                new Tag(912L, "Семантическая верстка", TagType.SKILL),
                new Tag(913L, "Flask", TagType.SKILL),
                new Tag(914L, "Fast API", TagType.SKILL),
                new Tag(915L, "RESTful API", TagType.SKILL),
                new Tag(916L, "RabbitMQ", TagType.SKILL),
                new Tag(917L, "Высоконагруженные системы", TagType.SKILL),
                new Tag(918L, "Оптимизация бизнес-процессов", TagType.SKILL),
                new Tag(919L, "Проектное планирование", TagType.SKILL),
                new Tag(920L, "Организация бизнес-процессов", TagType.SKILL),
                new Tag(921L, "Информационные технологии", TagType.SKILL),
                new Tag(922L, "Стратегическое планирование", TagType.SKILL),
                new Tag(923L, "Автоматизация процессов", TagType.SKILL),
                new Tag(924L, "Руководство стартапом", TagType.SKILL),
                new Tag(925L, "Продвижение проектов", TagType.SKILL),
                new Tag(926L, "GraphQL", TagType.SKILL),
                new Tag(927L, "Symfony", TagType.SKILL),
                new Tag(928L, "Разработка программного обеспечения", TagType.SKILL),
                new Tag(929L, "Apache Maven", TagType.SKILL),
                new Tag(930L, "Entity framework", TagType.SKILL),
                new Tag(931L, "Visual Studio", TagType.SKILL),
                new Tag(932L, ".NET Core", TagType.SKILL),
                new Tag(933L, "ASP.NET MVC", TagType.SKILL),
                new Tag(934L, "Windows Forms", TagType.SKILL),
                new Tag(935L, "Microsoft SQL Server", TagType.SKILL),
                new Tag(936L, "Microsoft SQL", TagType.SKILL),
                new Tag(937L, "Figma Design", TagType.SKILL),
                new Tag(938L, "Графический дизайн", TagType.SKILL),
                new Tag(939L, "Прототипирование", TagType.SKILL),
                new Tag(940L, "Дизайн мобильных приложений", TagType.SKILL),
                new Tag(941L, "Проектирование интерфейсов", TagType.SKILL),
                new Tag(942L, "Разработка фирменного стиля", TagType.SKILL),
                new Tag(943L, "Adobe After Effects", TagType.SKILL),
                new Tag(944L, "Разработка интерфейсов", TagType.SKILL),
                new Tag(945L, "Sketch", TagType.SKILL),
                new Tag(946L, "Исследование пользователя", TagType.SKILL),
                new Tag(947L, "Cinema 4d", TagType.SKILL),
                new Tag(948L, "Проектирование архитектуры приложений", TagType.SKILL),
                new Tag(949L, "Рекрутмент", TagType.SKILL)
        );

        tagRepo.saveAll(motivationTags);
        tagRepo.saveAll(professionTags);
        tagRepo.saveAll(skillTags);
    }
}
