databaseChangeLog:
  - changeSet:
      id: init-schema
      author: Aleksey Tumbaev
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createSequence:
            incrementBy: 50
            sequenceName: districts_seq
            startValue: 1
        - createTable:
            tableName: districts
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_districts
              - column:
                  name: name
                  type: VARCHAR(255)

        - createSequence:
            incrementBy: 50
            sequenceName: regions_seq
            startValue: 1
        - createTable:
            tableName: regions
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_regions
              - column:
                  name: name
                  type: VARCHAR(255)
              - column:
                  name: district_id
                  type: BIGINT
        - addForeignKeyConstraint:
            baseColumnNames: district_id
            baseTableName: regions
            constraintName: fk_regions_on_district_id
            referencedColumnNames: id
            referencedTableName: districts
            onDelete: RESTRICT

        - createSequence:
            incrementBy: 50
            sequenceName: cities_seq
            startValue: 1
        - createTable:
            tableName: cities
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_cities
              - column:
                  name: name
                  type: VARCHAR(255)
              - column:
                  name: region_id
                  type: BIGINT
        - addForeignKeyConstraint:
            baseColumnNames: region_id
            baseTableName: cities
            constraintName: fk_cities_on_region_id
            referencedColumnNames: id
            referencedTableName: regions
            onDelete: RESTRICT

        - createSequence:
            incrementBy: 50
            sequenceName: users_seq
            startValue: 1
        - createTable:
            tableName: users
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_users
              - column:
                  name: first_name
                  type: VARCHAR(255)
              - column:
                  name: last_name
                  type: VARCHAR(255)
              - column:
                  name: gender
                  type: VARCHAR(255)
              - column:
                  name: age
                  type: INT
              - column:
                  name: free_link
                  type: VARCHAR(255)
              - column:
                  name: own_link
                  type: VARCHAR(255)
              - column:
                  name: about_me
                  type: VARCHAR(255)
              - column:
                  name: date_of_registration
                  type: timestamp
              - column:
                  name: city_of_residence_id
                  type: BIGINT
              - column:
                  name: telegram
                  type: VARCHAR(255)
                  constraints:
                    unique: true
                    uniqueConstraintName: uc_users_telegram
              - column:
                  name: role
                  type: VARCHAR(255)
        - addForeignKeyConstraint:
            baseColumnNames: city_of_residence_id
            baseTableName: users
            constraintName: fk_users_on_city_of_residence_id
            referencedColumnNames: id
            referencedTableName: cities
            onDelete: SET NULL

        - createSequence:
            incrementBy: 50
            sequenceName: ads_seq
            startValue: 1
        - createTable:
            tableName: ads
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_ads
              - column:
                  name: title
                  type: VARCHAR(255)
              - column:
                  name: type
                  type: VARCHAR(255)
              - column:
                  name: user_id
                  type: BIGINT
              - column:
                  name: free_link
                  type: VARCHAR(255)
              - column:
                  name: own_link
                  type: VARCHAR(255)
              - column:
                  name: contacts
                  type: VARCHAR(255)
              - column:
                  name: details
                  type: VARCHAR(255)
              - column:
                  name: visibility
                  type: VARCHAR(255)
              - column:
                  name: creation_date
                  type: timestamp
        - addForeignKeyConstraint:
            baseColumnNames: user_id
            baseTableName: ads
            constraintName: fk_ads_on_user_id
            referencedColumnNames: id
            referencedTableName: users
            onDelete: CASCADE

        - createSequence:
            incrementBy: 50
            sequenceName: tags_seq
            startValue: 1
        - createTable:
            tableName: tags
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_tags
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    unique: true
                    uniqueConstraintName: uc_tags_name
              - column:
                  name: type
                  type: VARCHAR(255)

        - createSequence:
            incrementBy: 50
            sequenceName: ad_competence_level_tags_seq
            startValue: 1
        - createTable:
            tableName: ad_competence_level_tags
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_ad_competence_level_tags
              - column:
                  name: competence_level
                  type: INT
              - column:
                  name: ad_id
                  type: BIGINT
              - column:
                  name: tag_id
                  type: BIGINT
        - addForeignKeyConstraint:
            baseColumnNames: ad_id
            baseTableName: ad_competence_level_tags
            constraintName: fk_ad_competence_level_tags_on_ad_id
            referencedColumnNames: id
            referencedTableName: ads
            onDelete: CASCADE
        - addForeignKeyConstraint:
            baseColumnNames: tag_id
            baseTableName: ad_competence_level_tags
            constraintName: fk_ad_competence_level_tags_on_tag_id
            referencedColumnNames: id
            referencedTableName: tags
            onDelete: CASCADE
